#!/usr/local/bin/haserl --shell=lua
Content-type: text/html

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <title>GSM73xx Logs</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="../style.css" />
</head>

<body>

<div id="header">

<% 
   require "web_common"
   require "ui_utils"
   require "ui_cs_op"
   print(top_matter)
%>

    <div id="menu">

        <ul id="main">
            <li id="m-system"><a href="settings"><span>System</span></a></li>
            <li id="m-monitoring" class="active"><a href="portstats"><span>Monitoring</span></a></li>
            <li id="m-maintenance"><a href="upload"><span>Maintenance</span></a></li>
            <li id="m-help"><a href="help"><span>Help</span></a></li>
        </ul>

        <ul id="sub">
            <li><a href="portstats"><span>Port Statistics</span></a></li>
            <li><a href="port"><span>Port Status</span></a></li>
            <li><a href="flowtable"><span>Flow Table</span></a></li>
            <li class="active last"><a href="logs"><span>Logs</span></a></li>
        </ul>

    </div>

</div>

<div id="container">

    <div id="sidebar">

        <ul>
            <li><a href="#">OpenFlow Protocol Daemon</a></li>
            <li><a href="#">OpenFlow Switch Daemon</a></li>
            <li><a href="#">Command Server</a></li>
            <li><a href="#">Driver Debug</a></li>
        </ul>

    </div>

    <div id="content">

<h2>Logs</h2>

<form name="input" action="logs" method="POST">

<%
   selected = "ofproto"
   if FORM and FORM.log then selected = FORM.log end

   content = ""
   if ENV["REQUEST_METHOD"] == "POST" then
      if FORM.log == "drvdbg" then
         status, results, err_str = cs_info_get()
         if results == nil or #results == 0 then
            content = "Unable to retrieve information from driver\n"
         else
            for i, entry in ipairs(results) do
               content = content .. entry.info .. "\n"
            end
         end
      elseif FORM.log == "cxnlog" then
         entries = get_ctrl_history()
         for i,ent in ipairs(entries) do
            content = content .. os.date(ent.time) .. ": " ..
               ent.state .. ": " .. ent.ctrl_ip .. "\n"
         end
      else
         local filename = "/local/logs/" .. FORM.log .. ".log"
         content = read_file(filename)
         if not content then
            content = "ERROR: Could not open " .. tostring(filename)
         end
      end
   end
%>

<p>
<select name="log" size="1" >
<option name="cmdsrv" 
<% get_chk_val(selected, "cmdsrv", "selected") %>
value="cmdsrv">Command Server</option>
<option name="ofproto" 
<% get_chk_val(selected, "ofproto", "selected") %>
value="ofproto">OpenFlow Protocol Daemon</option>
<option name="ofswd" 
<% get_chk_val(selected, "ofswd", "selected") %>
value="ofswd">OpenFlow Switch Daemon</option><br>
<option name="cmdsrv" 
<% get_chk_val(selected, "cxnlog", "selected") %>
value="cxnlog">Controller Connection History</option>
<option name="drvdbg" 
<% get_chk_val(selected, "drvdbg", "selected") %>
value="drvdbg">Driver Debug</option>
</select>

<input type="submit" value="Refresh Log" />
</form></p>

<%
   if content then
      print("<h2>")
      if FORM.log == "cmdsrv" then
         print("Command Server Log<\h2>")
      elseif FORM.log == "ofproto" then
         print("Protocol Daemon Log<\h2>")
      elseif FORM.log == "ofswd" then
         print("Switch Datapath Daemon Log<\h2>")
      elseif FORM.log == "cxnlog" then
         print("Controller Connection History<\h2>")
      elseif FORM.log == "drvdbg" then
         print("Driver Debug Log<\h2>")
      end
      print("</h2>Current time: ".. os.date().. "<br>")
      print("<textarea cols='85' rows='30' readonly>")
      print(content)
      print("</textarea>")
   end
%>

    </div>

<div class="clearer"></div>
<div id="btm"></div>
</div>

<div id="footer">

    <p id="copyright">Copyright &copy; 1996-2011 Netgear &reg;</p>

</div>

</body>
</html>


