#!/usr/local/bin/haserl --shell=lua
Content-type: text/html

<!-- Copyright 2011 Big Switch Networks -->

<% 
   require "log_common"
   require "ui_utils"
   require "ui_cs_op"

   content = ""
   entries = get_ctrl_history()
   if entries then
      for i,ent in ipairs(entries) do
         content = content .. os.date(ent.time) .. ": " .. ent.state .. ": " .. ent.ctrl_ip .. "\n"
      end
   else
      content = "Could not generate controller connection history"
   end
   print_log_page_content("ofcxnlog", content)
%>
