#!/usr/local/bin/haserl --shell=lua -u 16000
Content-type: text/html

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <title>GSM73xx Upload</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="../style.css" />
</head>

<body>

<div id="header">

<%
   require("ui_utils")
%>


<% 
   require "web_common"

   print(top_matter)

%>


    <div id="menu">

        <ul id="main">
            <li id="m-system"><a href="settings"><span>System</span></a></li>
            <li id="m-monitoring"><a href="portstats"><span>Monitoring</span></a></li>
            <li id="m-maintenance" class="active"><a href="upload"><span>Maintenance</span></a></li>
            <li id="m-help"><a href="help"><span>Help</span></a></li>
        </ul>

        <ul id="sub">
            <li class="active"><a href="upload"><span>Upload</span></a></li>
            <li><a href="reflash"><span>Reflash</span></a></li>
            <li><a href="reboot"><span>Reboot</span></a></li>
            <li><a href="restart"><span>Restart Processes</span></a></li>
            <li class="last"><a href="integrity"><span>Integrity</span></a></li>
        </ul>

    </div>

</div>

<div id="container">

    <div id="sidebar">

        <ul>
            <li class="active"><a href="upload">Upload</a></li>
        </ul>

    </div>

    <div id="content">

<h2>Upload New Firmware</h2>

<p>On this page you can upload new firmware to the switch using your web browser or TFTP. The target file will be stored on the switch in /tmp/mtd0image.</p>

<p><strong>NOTE: This page will refresh when the upload is complete</strong> <form method='POST' enctype='multipart/form-data' action='upload2'></p>

<h3 class="narrow">Upload New Firmware</h3>
<div class="sm">

<table class="dotted">
<tr>
    <td colspan="2">

        <p><strong><input type="radio" name="up_mode" value="http" /> Use Browser</strong></p>
        <p>File to upload: <input type="file" name="upfile"></p>

    </td>
</tr>
<tr>
    <td colspan="2">

        <p><strong><input type="radio" name="up_mode" value="tftp" /> Use TFTP</strong></p>

    </td>
</tr>
<tr>
    <td>TFTP IP address:</td>
    <td><input type="input" name="tftp_ip" class="field-01" /></td>
</tr>

<tr>
    <td>File name on TFTP server:</td>
    <td><input type="input" name="filename" value="mtd0image" class="field-01" /></td>
</tr>

<tr>
    <td colspan="2">

        <p><input type="submit" value="Press" /> to upload the file</p>

    </td>
</tr>
</table>

</form>
</div>

    </div>

<div class="clearer"></div>
<div id="btm"></div>
</div>

<div id="footer">

    <p id="copyright">Copyright &copy; 1996-2011 Netgear &reg;</p>

</div>

</body>
</html>
