#!/usr/local/bin/haserl --shell=lua -u 16000
Content-type: text/html

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <title>GSM73xx Upload</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="../style.css" />

<%
   require("ui_utils")
%>

</head>

<body>

<div id="header">

<%
   require "web_common"

   print(top_matter)

%>

    <div id="menu">

        <ul id="main">
            <li id="m-system"><a href="settings"><span>System</span></a></li>
            <li id="m-monitoring"><a href="portstats"><span>Monitoring</span></a></li>
            <li id="m-maintenance" class="active"><a href="upload"><span>Maintenance</span></a></li>
            <li id="m-help"><a href="help"><span>Help</span></a></li>
        </ul>

        <ul id="sub">
            <li class="active"><a href="upload"><span>Upload</span></a></li>
            <li><a href="reflash"><span>Reflash</span></a></li>
            <li><a href="reboot"><span>Reboot</span></a></li>
            <li><a href="restart"><span>Restart Processes</span></a></li>
            <li class="last"><a href="integrity"><span>Integrity</span></a></li>
        </ul>

    </div>

</div>

<div id="container">

    <div id="sidebar">

        <ul>
            <li class="active"><a href="upload">Upload</a></li>
        </ul>

    </div>

    <div id="content">


<%

   if ENV["REQUEST_METHOD"] == "POST" then
      os.execute("rm -f /tmp/mtd0image.md5")
      if FORM.up_mode == "tftp" then
         -- TODO Cleanse filename
         cmd = "cd /tmp && tftp -r " .. FORM.filename
         cmd = cmd .. " -g " .. FORM.tftp_ip
         rv = os.execute(cmd)
         if rv == 0 and FORM.filename ~= "mtd0image" then
            os.execute("mv /tmp/" .. FORM.filename .. " /tmp/mtd0image")
         end
      else -- browser
         -- Move to known image name
         rv = os.execute("mv " .. FORM.upfile .. " /tmp/mtd0image")
      end
      if rv == 0 then
         rv = os.execute("md5sum /tmp/mtd0image > /tmp/mtd0image.md5")
      end
      if rv ~= 0 then
         print("<h2><font color=red>Error uploading file.</font></h2>")
      else
         md5val = read_file("/tmp/mtd0image.md5")
         if not md5val then
            print("<h2><font color=red>Error generating md5sum.</font></h2>")
         else
            md5val = string.gsub(md5val, ' .*', '')
            print("<h2><font color=green>Uploaded file with MD5: " ..
                  tostring(md5val) .. "</font></h2>")
         end
      end
   end

%>

        <h2><a href="reflash">Proceed to reflash operation</a></h2>

    </div>

<div class="clearer"></div>
<div id="btm"></div>
</div>

<div id="footer">

    <p id="copyright">Copyright &copy; 1996-2011 Netgear &reg;</p>

</div>

</body>
</html>


</body>
</html>
