# Copyright 2011,  Big Switch Networks
#
# Makefile for Command Server library or standalone test program

ifndef CROSS_COMPILE
# If no Cross Compile just use host makefile
include host.mk

else # Cross compile

include cross.mk

endif  # End of cross compile make defines
