#!/usr/bin/lua
--
-- Copyright 2011 Big Switch Networks
--
-- Usage:  html_gen.lua <hw-desc> <firmware-desc>

page_template = [[
<!-- Copyright 2011 Big Switch Networks -->
<!-- Automatically generated by gen_html.lua -->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Indigo OpenFlow Switch</title>

  <link type="text/css"  href="/static/jq-ui-ind/css/custom-theme/jquery-ui-1.8.9.custom.css" rel="stylesheet" /> 
  <link rel="stylesheet" href="/css/indigo.css" />
  <link rel="shortcut icon" href="/favicon.ico" />
  <link rel="icon" type="image/png" href="/favicon.png" />

  <script type="text/javascript" src="/static/jq-ui-ind/js/jquery-1.4.4.min.js"></script>
  <script type="text/javascript" src="/static/jq-ui-ind/js/jquery-ui-1.8.9.custom.min.js"></script>
    
  <script type="text/javascript" src="/static/jq-plugins/jquery.dataTables.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      $( "#coreui-base-leftmenu" ).accordion({
        active : $("#__PAGE_NAME__")
      });

      $( "#coreui-base-leftmenu" ).bind( "accordionchange", function(event, ui) {
        var url = ui.newHeader.find("a").attr("href"); //crumby way to fish the app name back out
        window.location.replace(url)
      });

      $( "#coreui-base-tabs" ).tabs({
        ajaxOptions: {
          error: function( xhr, status, index, anchor ) {
          $( anchor.hash ).html("Error: Couldn't load this tab."); }
        },
        panelTemplate: '<div style="background-color:#fff;"></div>'
      });
    });
  </script>
</head>

<body>
  <div id="content">
    <table width=100% >
      <tr>
        <td valign=bottom><p style="font-weight: bold; font-size: 150%; color: #110f80;" >
          __HARDWARE_DESC__<br>__FIRMWARE_DESC__</td>
        <td align=right><img src="/img/ind_gem_logo.png"></td>
      </tr>
    </table>
    <div style="height:1px;background-color:lightgray;clear:both;" ></div>
    <div style="height:1px;background-color:darkgray;clear:both; margin-bottom:10px;    " ></div>
    <table width=100% >
      <tr>
        <td valign="top" id="base-appmenu-td">
          <div id="coreui-base-leftmenu">
            <h3 id="configuration"><a href="/configuration.html">Configuration</a></h3>
            <div>
              <p>
                Change settings such as the controller IP address, controller port, or 
                switch IP address.
              </p>
            </div>
            <h3 id="monitoring"><a href="/monitoring.html">Monitoring</a></h3>
            <div>
              <p>
                Switch monitoring functions including port stats and flow table.
              </p>
            </div>
            <h3 id="control"><a href="/control.html">Switch Control</a></h3>
            <div>
              <p>
                Switch control functions including loading a new image, restarting
                tasks and rebooting the switch.
              </p>
            </div>
            <h3 id="logs"><a href="/logs.html">Logs and Info</a></h3>
            <div>
              <p>
                Display logs and other debug information
              </p>
            </div>
            <h3 id="documentation"><a href="/documentation.html">Documentation</a></h3>
            <div>
              <p>
                Information about Indigo
              </p>
            </div>
          </div>
          <br>
        </td>
        <td id="base-vline-td"><td>
        <td valign="top" id="base-content-td">
          <div id="coreui-base-tabs" style="background-color: #fff;">
            <ul>
__PAGE_TABS_LIST__
            </ul>
          </div>
        </td>
      </tr>
    </table>
  </div>
</body>
</html>
]]

tabs = {}

tabs.monitoring = [[
              <li class="coreui-base-tablabel"><a href="/cgi-bin/flowtable">Flowtable</a></li>
              <li class="coreui-base-tablabel"><a href="/cgi-bin/portstats">Port Statistics</a></li>
              <li class="coreui-base-tablabel"><a href="/cgi-bin/port">Port Status</a></li>
]]

tabs.configuration = [[
              <li class="coreui-base-tablabel"><a href="/cgi-bin/settings">System Settings</a></li>
              <li class="coreui-base-tablabel"><a href="/cgi-bin/ofd_settings">Daemon Settings</a></li>
]]

tabs.documentation = [[
              <li class="coreui-base-tablabel"><a href="/cgi-bin/doc">Documentation</a></li>
]]

tabs.control = [[
              <li class="coreui-base-tablabel"><a href="/cgi-bin/upload">Upload New Image</a></li>
              <li class="coreui-base-tablabel"><a href="/cgi-bin/reboot">Reboot the System</a></li>
              <li class="coreui-base-tablabel"><a href="/cgi-bin/restart">Restart Daemons</a></li>
]]

tabs.logs = [[
              <li class="coreui-base-tablabel"><a href="/cgi-bin/ofcxnlog">Connection History</a></li>
              <li class="coreui-base-tablabel"><a href="/cgi-bin/ofprotolog">Controller Connection Log</a></li>
              <li class="coreui-base-tablabel"><a href="/cgi-bin/ofswdlog">Switch Daemon Log</a></li>
              <li class="coreui-base-tablabel"><a href="/cgi-bin/drvdbg">Driver Debug Information</a></li>
              <li class="coreui-base-tablabel"><a href="/cgi-bin/cmdsrvlog">Command Server Log</a></li>
]]


hw_desc = arg[1] or "Unknown"
fw_desc = arg[2] or "Unknown"

-- Platform specific changes
if string.find(hw_desc, "3240") or string.find(hw_desc, "LB4") then
   -- Can not upload new image on LB4G
   tabs.control = [[
              <li class="coreui-base-tablabel"><a href="/cgi-bin/reboot">Reboot the System</a></li>
              <li class="coreui-base-tablabel"><a href="/cgi-bin/restart">Restart Daemons</a></li>]]
end

for k,v in pairs(tabs) do
   filename = k .. '.html'
   print("Generating " .. filename)
   page_content = string.gsub(page_template, "__PAGE_NAME__", k)
   page_content = string.gsub(page_content, "__HARDWARE_DESC__", hw_desc)
   page_content = string.gsub(page_content, "__FIRMWARE_DESC__", fw_desc)
   page_content = string.gsub(page_content, "__PAGE_TABS_LIST__", v)

   file = io.open(filename, "w")

   if not file then
      print("Could not open file " .. filename)
      os.exit(1)
   end
   file:write(page_content)
   io.close(file)
end
