#!/bin/sh
#
# Copyright 2011 Big Switch Networks
#
# Script to restart OpenFlow related daemons
#
source /etc/find-env

echo "OpenFlow Switch Restart"
echo "Killing protocol daemon"
killall -q ofprotocol.sh
killall -q ofprotocol
echo "Killing switch daemon"
killall -q ofswd
sleep 1
killall -q ofswd-run
echo "Removing existing SDK config files"
rm -f $client_root/config.bcm $client_root/rc.soc
echo "Delaying restart for 5 seconds"
sleep 5

if test "$disable_sysconf" == "yes" ; then 
    echo "disable_sysconf is yes.  Manual configuration required.  Exiting."
    exit 0
fi

echo "Starting ofswd"
/sbin/ofswd-setup

echo "Starting ofprotocol"
/sbin/ofprotocol.sh &

touch /tmp/.sys-restart
