#!/bin/sh
#
# Copyright 2011 Big Switch Networks
#
# Script to run ofswd in the foreground
# If ofswd exits, the re-run script is called in this context
# which re-forks and calls this script again
#

source /etc/find-env

log_file=$log_dir/ofswd.log

if test -e $log_file; then
    # Save log file once in .save, always in .old
    if ! test -e $log_file.save; then
        cp $log_file $log_file.save
    fi
    mv $log_file $log_file.old
fi

if test -e $log_dir/cmdsrv.log; then
    mv $log_dir/cmdsrv.log $log_dir/cmdsrv.log.old
fi

echo "Starting ofswd" > $log_file

# On the Netgear, need to reconfigure network after restarting
# So re-call start_ofswd if this fails, rather then looping
date >> $log_file
cd /local
/sbin/ofswd < /dev/null >> $log_file 2>&1
# If ofswd returns, something went wrong
sleep 1
# Clear the configuration to force re-config
rm $client_root/config.bcm
echo "ofswd terminated" >> $log_file
echo "Restarting ofswd in 10 seconds" >> $log_file
sleep 10

# Re-rerun ofswd-setup
exec /sbin/ofswd-setup

