#!/bin/sh
#
# Copyright 2011 Big Switch Networks
#
# Set up the init scripts for ofswd and call ofswd-exec as
# a background process.  ofswd-exec runs invokes ofswd in
# its foreground.  If ofswd exits, ofswd-exec re-invokes
# ofswd-setup.
#

source /etc/find-env

# Copy rc.soc and config.bcm init files to client root directory
if test -e $client_rc_soc; then
    if test $client_rc_soc != $client_root/rc.soc; then
        cp $client_rc_soc $client_root/rc.soc
    fi
else
    echo "ERROR: Could not find rc.soc init file for BCM shell; exiting"
    exit 1
fi

# Update config.bcm with environment configuration.
# Do this only if the origin of config.bcm is /etc
#

if test -e $client_config_bcm; then
    if test $client_config_bcm != $client_root/config.bcm; then
        cp $client_config_bcm $client_root/config.bcm
    fi

    # If starting w/default config.bcm, add necessary params
    if test $client_config_bcm == /etc/config.bcm; then
        # Boot args conveyed to ofswd through config.bcm:
        #   datapath ID, portlist, init_port_state, add_port_state
        if test -n "$datapath_id" ; then
            echo "Setting DPID to $datapath_id"
            echo dpid=$datapath_id >> $client_root/config.bcm
        fi
        if test "$dp_mgmt_oob" == "yes"; then
            echo "Setting dp_mgmt_oob to $dp_mgmt_oob"
            echo dp_mgmt_oob=$dp_mgmt_oob >> $client_root/config.bcm
        fi
        if test "$dp_mgmt_port_fixed" == "yes"; then
            if test -n "$dp_mgmt_port" ; then 
                echo "Setting dp_mgmt_port to $dp_mgmt_port"
                echo dp_mgmt_port=$dp_mgmt_port >> $client_root/config.bcm
            fi
        fi
        # TBD:
        #if test -n "$dp_mgmt_vid" ; then 
        #    echo "Setting dp_mgmt_vid to $dp_mgmt_vid"
        #    echo dp_mgmt_vid=$dp_mgmt_vid >> $client_root/config.bcm
        #fi
        if test -n "$tap0_mac" ; then 
            echo "Setting tap0_mac (dp_mgmt_mac)"
            echo dp_mgmt_mac=$tap0_mac >> $client_root/config.bcm
        fi
        if test -n "$portlist" ; then 
            echo "Setting port list to $portlist"
            echo portlist=$portlist >> $client_root/config.bcm
        fi
        if test -n "$init_port_state" ; then 
            echo "Setting init_port_state to $init_port_state"
            echo init_port_state=$init_port_state >> $client_root/config.bcm
        fi
        if test -n "$add_port_state" ; then 
            echo "Setting add_port_state to $add_port_state"
            echo add_port_state=$add_port_state >> $client_root/config.bcm
        fi
    else
        echo "NOTE: config.bcm exists. Not updating config parameters"
    fi
else
    echo "WARNING: No config.bcm file found"
fi

cd $client_root
echo "Starting ofswd in $client_root"
ofswd-run &
echo "ofswd running"

if test -e /etc/inband-network; then
    echo "Delaying before configuring dp_mgmt interface"
    sleep 12  # Check this timing
    source /etc/inband-network
fi

