#!/bin/sh
#
# Script to remove a file from the overlay
#
# Non-absolute paths are relative to current directory
#

help="ovlremove <file>:  Remove a file from persistent overlay; Use ovlsave to commit."

if test -z "$1"; then
    echo $help
    exit 1
fi

if test -n "$2"; then
    echo $help
    exit 1
fi

if test "$1" == "-h"; then
    echo $help
    exit 0
fi

if test -z "`echo $1 | grep -e '^/'`"; then
    filename=`pwd`/$1
else
    filename=$1
fi

echo "Removing file $filename from persistent overlay"
if ! test -e $filename; then
    echo "Warning: $filename does not exist"
fi

in_file=`grep -e  "^$filename$" /etc/overlay-files`
if test -z "$in_file"; then
    echo "Warning: $filename not found in overlay file list"
else
    tmpfile=/tmp/overlay_tmp_file
    grep -v -e "^$filename$" /etc/overlay-files > $tmpfile
    mv $tmpfile /etc/overlay-files
fi

echo "Use ovlsave to commit change to the overlay"
