#!/bin/sh
#
# Copyright 2011 Big Switch Networks

################################################################
#
# OpenFlow Switch Setup
#
################################################################

echo "User mode OpenFlow executable selected"

source /etc/find-env

# Save old dhcp log
[ -e $log_dir/dhcp.log ] && mv $log_dir/dhcp.log $log_dir/dhcp.log.old

# Start up ofswd restart script
/sbin/ofswd-setup

# Run OpenFlow protocol daemon restart
/sbin/ofprotocol.sh &
sleep 1

echo "System Config File Complete"
