#!/bin/sh
#
# Script to add a file to the overlay
#
# Non-absolute paths are relative to current directory
#

help="ovladd <filename>:  Add a file to the persistent overlay."

if test -z "$1"; then
    echo $help
    exit 1
fi

if test -n "$2"; then
    echo $help
    exit 1
fi

if test "$1" == "-h"; then
    echo $help
    exit 0
fi

if test -z "`echo $1 | grep -e '^/'`"; then
    filename=`pwd`/$1
else
    filename=$1
fi

echo "Adding file $filename to persistent overlay"
if ! test -e $filename; then
    echo "Warning: $filename does not exist"
fi

echo $filename >> /etc/overlay-files

echo "Use ovlsave to commit change to the overlay"
