#!/usr/local/bin/haserl --shell=lua
Content-type: text/html

<!-- Copyright 2011 Big Switch Networks -->

<% 
   require "log_common"
   require "ui_utils"
   require "ui_cs_op"

   content = ""
   status, results, err_str = cs_info_get()
   if results == nil or #results == 0 then
      content = "Unable to retrieve information from driver\n"
   else
      for i, entry in ipairs(results) do
         content = content .. entry.info .. "\n"
      end
   end
   print_log_page_content("drvdbg", content)
%>
