#!/usr/local/bin/haserl --shell=lua
Content-type: text/html

<!-- Copyright 2011 Big Switch Networks -->

<% 
   require "web_common"
   require "ui_cs_op"
   require "ui_utils"
   require "ui_config"
%>

<html>
<head>
    <% print(common_includes) %>
	<script type="text/javascript">
	  $(document).ready(function(){
        $('#ofd_settings_form').ajaxForm({target: '#ofd_settings_content'});
	  });
	</script>
</head>

<body>
<div id="ofd_settings_content">

<%
   function chk_var(var)
      if var then print(tostring(var)) else print("not_set") end
   end

   -- TODO Validate text fields properly

   local cfg = { }

   if ENV["REQUEST_METHOD"] == "POST" then
      -- Populate config to save from form settings
      rv, err_str = config_save(FORM)
      if rv < 0 then
         print("<font color=red><b>")
         print("Error saving configuration: " .. err_str .. "</b></font>\n\n")
      else
         print("<font color=green><b>Configuration saved.</b></font><br><br>")
         print("<font color=red>Please <a href=\"/control.html#ui-tabs-3\">restart daemons</a></font>.")
      end
   end

   -- Refresh the system configuration into the cfg variable
   rv, err_str = config_read(cfg)
   if rv < 0 then
      print("<font color=red><b>")
      print("Error reading configuration: " .. err_str .. "</b></font>\n\n")
   end

%>

<form name="input" action="/cgi-bin/ofd_settings" method="POST" id="ofd_settings_form">
<table cellspacing="10">
<input type="hidden" name="switch_ip" value=<% chk_var(cfg.switch_ip) %> />
<input type="hidden" name="netmask" value=<% chk_var(cfg.netmask) %> />
<input type="hidden" name="gateway" value=<% chk_var(cfg.gateway) %> />
<input type="hidden" name="system_ref" value=<% chk_var(cfg.system_ref) %> />
<tr><td>OpenFlow Controller IP address: </td>
  <td>
<input type="text" name="controller_ip" value=<% chk_var(cfg.controller_ip) %> />
</td></tr>
<tr><td>OpenFlow Controller TCP port:</td>
<td>
<input type="text" name="controller_port" 
       value=<% chk_var(cfg.controller_port) %> />
</td></tr>
<tr><td>Datapath ID of this switch: </td>
<td>
<input type="text" name="datapath_id" value=<% chk_var(cfg.datapath_id) %> />
</td></tr>
<tr><td>Fail open/close: </td>
<td>
<input type="radio" name="fail_mode" value="open" 
<% get_chk_val(cfg.fail_mode, "open") %> />open <br />
<input type="radio" name="fail_mode" value="closed"
<% get_chk_val(cfg.fail_mode, "closed") %> />closed <br />
</td></tr>
<tr><td>
Log level:
</td><td>
<select name="log_level" size="1" >
<option name="none" <% get_chk_val(cfg.log_level, "none", "selected") %> >none</option>
<option name="error" <% get_chk_val(cfg.log_level, "error", "selected") %> >error</option>
<option name="warn" <% get_chk_val(cfg.log_level, "warn", "selected") %> >warn</option>
<option name="info" <% get_chk_val(cfg.log_level, "info", "selected") %> >info</option>
<option name="verbose" <% get_chk_val(cfg.log_level, "verbose", "selected") %> >verbose</option>
<option name="verbose" <% get_chk_val(cfg.log_level, "vverb", "selected") %> >vverb</option>
</select>
</td></tr>
<tr><td>
<input type="submit" value="Save Configuration" /></td>
<td>
</tr>
</table>
</form>

</body>
</html>
