#!/usr/local/bin/haserl --shell=lua
Content-type: text/html

<!-- Copyright 2011 Big Switch Networks -->

<% 
   require "log_common"
   require "platform"
   require "ui_utils"

   local filename = Platform.log_dir .. "/ofproto.log"
   content = read_file(filename)
   if not content then
      content = "ERROR: Could not open " .. tostring(filename)
   end
   print_log_page_content("ofprotolog", content)
%>
