#!/usr/local/bin/haserl --shell=lua
Content-type: text/html

<!-- Copyright 2011 Big Switch Networks -->

<% 
   require "web_common"
   require "ui_cs_op"
   require "ui_utils"
%>


<html>
<head>
    <% print(common_includes) %>
	<script type="text/javascript">
	  $(document).ready(function(){
        $('#reboot_form').ajaxForm({target: '#reboot_content'});
	  });
	</script>
</head>

<body>
<div id="reboot_content">

<%
   if ENV["REQUEST_METHOD"] == "POST" then
      print('<meta http-equiv="REFRESH" content="45;url=/configuration.html">')
      pagecontent = [[
<h1>Rebooting the switch in 5 seconds</h1>
<h2>This will take about one minute.</h2>
<h2>You will need to reload the page once the switch has rebooted</h2>
<h2><a href="/configuration.html">Click here to return to configuration</a></h2>
]]
      os.execute("sleep 5 && reboot &")
   else
      pagecontent = [[
<h2>Are you sure you want to reboot the switch?</h2>
<br>
<style type=text/css>
input.red {background-color: #cc0000; font-weight: bold; font-size: 12px; color: white;}
</style>

<br>
<form name="input" action="/cgi-bin/reboot" method="POST" id="reboot_form">
<input class="red" type="submit" value="REBOOT SWITCH" />
</form>
]]
   end

   print(pagecontent)

%>

</div>
</body>
</html>
